"""empty message

Revision ID: f39f0bd49dc1
Revises: 
Create Date: 2018-09-05 16:09:53.826847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f39f0bd49dc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('letter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('letter', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('u_name', sa.String(length=32), nullable=True),
    sa.Column('u_password', sa.String(length=256), nullable=True),
    sa.Column('u_email', sa.String(length=64), nullable=True),
    sa.Column('u_active', sa.Boolean(), nullable=True),
    sa.Column('u_token', sa.String(length=256), nullable=True),
    sa.Column('u_promission', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('u_email'),
    sa.UniqueConstraint('u_name')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regionName', sa.String(length=16), nullable=True),
    sa.Column('cityCode', sa.Integer(), nullable=True),
    sa.Column('pinYin', sa.String(length=128), nullable=True),
    sa.Column('letter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['letter'], ['letter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city')
    op.drop_table('user_model')
    op.drop_table('letter')
    # ### end Alembic commands ###
